### ISSUE TITLE
Does not respect scrolloff

### ISSUE THREAD

**Issue by ttytm** [bmalehorn/vscode-scroll-viewport#5]
Hello your extension solves quiet some problems I'm glad I found it a while ago. Thanks for developing it 🙂.

Did you try to implement support for the scrolloff / surrounding lines setting?

```js
.getConfiguration('editor').get<number>('cursorSurroundingLines', 0);
```

Is it that method that gets the setting? But I worry that I will probably not be able to implement it as I do not understand that much here :/. But I've noticed VSCode/Vim has got it working well. ut this is the classic scroll action. 

[VSCodeVim/.../actions/commands/scroll.ts](https://github.com/VSCodeVim/Vim/blob/master/src/actions/commands/scroll.ts)

Do you think it's possible for the scroll viewport extension?

**Comment by bmalehorn** [comment]
Hey @tobealive, thanks for the suggestion! This has now been addressed in https://github.com/bmalehorn/vscode-scroll-viewport/commit/561d3bd82a182a9e5e42b45a70d53321ae0c11c2 - scroll viewport now obeys `editor.cursorSurroundingLines`. This also fixes a bug where scroll viewport will scroll by more than the configured amount.

Note that the effective number of surrounding lines when scrolling upwards is always at least 5, and downwards is always at least 1.

Let me know if you see any problems with the vscode extension's behavior.
